### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by simon-tannai** [cedrickchee/rnnoise-nodejs#5]
Hello @cedrickchee,

I'm trying to install this NPM module but I got this error when I ran `npm i --save `:
```bash
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/cedrickchee/rnnoise-nodejs/releases/download/0.1.8/node-v83-linux-x64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/home/nowis/Documents/_CODE/jarvis-msbf-nlpjs/stt-srv/sandbox/DeepSpeech-examples/nodejs_wav/node_modules/rnnoise/node_modules/node-pre-gyp/lib/install.js:142:27)
node-pre-gyp ERR! stack     at PassThrough.emit (events.js:327:22)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/nowis/Documents/_CODE/jarvis-msbf-nlpjs/stt-srv/sandbox/DeepSpeech-examples/nodejs_wav/node_modules/needle/lib/needle.js:508:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:422:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:509:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:309:12)
node-pre-gyp ERR! System Linux 5.8.0-41-generic
node-pre-gyp ERR! command "/home/nowis/.nvm/versions/node/v14.15.4/bin/node" "/home/nowis/Documents/_CODE/jarvis-msbf-nlpjs/stt-srv/sandbox/DeepSpeech-examples/nodejs_wav/node_modules/rnnoise/node_modules/.bin/node-pre-gyp" "install" "--update-binary" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /home/nowis/Documents/_CODE/jarvis-msbf-nlpjs/stt-srv/sandbox/DeepSpeech-examples/nodejs_wav/node_modules/rnnoise
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/cedrickchee/rnnoise-nodejs/releases/download/0.1.8/node-v83-linux-x64.tar.gz
neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm WARN deepspeech-nodejs_wav@1.0.0 No repository field.
npm WARN deepspeech-nodejs_wav@1.0.0 license should be a valid SPDX license expression
```

Is there any solution to fix it ?
Thanks :)

**Comment by cedrickchee** [comment]
Hi @simon-tannai,

What is your Node.js version? The library currently only supports Node.js 8 or 10. Could you try installing it using Node.js 10?

It's been more than a year since I last updated this library. I haven't got time to update it to support Node.js beyond version 10. Contributors are welcome.

**Comment by simon-tannai** [comment]
@cedrickchee That's right, it's working fine with the version 10 of Node.js :+1:  
Thanks :)
